### ISSUE TITLE
After Restart, need to zoom out

### ISSUE THREAD

**Issue by joshk6656** [tellomichmich/PokeNoxBot#39]
When the bot restarts the game, the zoom goes back to default so it needs to zoom out.

**Comment by Bolo30** [comment]
I had same issue and found a workaround.

You need to add "sendevent" in the file "zommout.txt", because sometimes the virtual input change from "event7" to "event8" or "event9".

You can use the zoomout.txt file attached to this message, it contains all possibility.

[Zoomout.txt](https://github.com/tellomichmich/PokeNoxBot/files/434511/Zoomout.txt)

**Comment by joshk6656** [comment]
Closing this issue, as its a duplicate of https://github.com/tellomichmich/PokeNoxBot/issues/29
